name: remote ssh command to copy files to nfs
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ECS_DEV_HOST_DNS }}
        username: ${{ secrets.ECS_DEV_USERNAME }}
        key: ${{ secrets.ECS_DEV_SSH_KEY }}
        port: 22
        #-R recursively copies all the files in the destination, -u ensures only new files are copied over, -p preserve timestamp
        script: sudo cp -R -u -p /var/moodledata/. /nfs-mount-point/moodledata
    - name: clearing cache for prod server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ECS_PROD_HOST_DNS }}
        username: ${{ secrets.ECS_PROD_USERNAME }}
        key: ${{ secrets.ECS_DEV_SSH_KEY }}
        port: 22
        script: php /var/www/html/youclass-moodle/admin/cli/purge_caches.php
